spring.application.name=MuqarariPlus

# Server Port (Dynamic for Cloud Railway, 8080 for Localhost)
server.port=${PORT:8080}

# Database Properties (Dynamic for Cloud, Localhost fallback)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/moqarariplus?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Web and Thymeleaf properties
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Locale settings (Fallback)
spring.web.locale=ar

# i18n MessageSource Binding
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Multipart File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB